export const hauVaultAbi = [
  {
    type: "function",
    stateMutability: "view",
    name: "credentials",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [
      { name: "studentName", type: "string" },
      { name: "program", type: "string" },
      { name: "institution", type: "string" },
      { name: "credentialTitle", type: "string" },
      { name: "credentialType", type: "string" },
      { name: "issuedDate", type: "string" },
      { name: "metadataURI", type: "string" },
      { name: "studentNumber", type: "string" },
      { name: "batch", type: "string" },
      { name: "email", type: "string" },
      { name: "location", type: "string" },
      { name: "credentialTypes", type: "string" },
      { name: "active", type: "bool" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "tokenIdByStudentNumber",
    inputs: [{ name: "", type: "string" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    name: "issueCredential",
    inputs: [
      { name: "to", type: "address" },
      {
        name: "data",
        type: "tuple",
        components: [
          { name: "studentName", type: "string" },
          { name: "program", type: "string" },
          { name: "institution", type: "string" },
          { name: "credentialTitle", type: "string" },
          { name: "credentialType", type: "string" },
          { name: "issuedDate", type: "string" },
          { name: "metadataURI", type: "string" },
          { name: "studentNumber", type: "string" },
          { name: "batch", type: "string" },
          { name: "email", type: "string" },
          { name: "location", type: "string" },
          { name: "credentialTypes", type: "string" },
          { name: "active", type: "bool" },
        ],
      },
    ],
    outputs: [{ name: "tokenId", type: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "totalSupply",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ name: "account", type: "address" }],
  },
  { type: "error", name: "Error", inputs: [{ name: "message", type: "string" }] },
  { type: "error", name: "ERC721InvalidReceiver", inputs: [{ name: "receiver", type: "address" }] },
] as const;

